<a href="https://colab.research.google.com/github/chandupradeep18/Python_pandas/blob/main/Intro_to_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
bios='https://github.com/KeithGalli/complete-pandas-tutorial/blob/master/data/bios.csv'
noc_regions='https://github.com/KeithGalli/complete-pandas-tutorial/blob/master/data/noc_regions.csv'
olympics='https://github.com/KeithGalli/complete-pandas-tutorial/blob/master/data/olympics-data.xlsx'
results='https://github.com/KeithGalli/complete-pandas-tutorial/blob/master/data/results.csv'
feather='https://github.com/KeithGalli/complete-pandas-tutorial/blob/master/data/results.feather'
parquet='https://github.com/KeithGalli/complete-pandas-tutorial/blob/master/data/results.parquet'

In [ ]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21],[22,23,24],[25]]) #pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['X','Y','Z'],index=['A','B','C'])
df.columns=['X','Y','Z'] #add Columns Names to Data set
df.index=['A','B','C','D','E','F','G','H','I'] #add Index Names to Data set
df

    X     Y     Z
A   1   2.0   3.0
B   4   5.0   6.0
C   7   8.0   9.0
D  10  11.0  12.0
E  13  14.0  15.0
F  16  17.0  18.0
G  19  20.0  21.0
H  22  23.0  24.0
I  25   NaN   NaN

In [ ]:
df.head() #return First five Row From The data Set

    X     Y     Z
A   1   2.0   3.0
B   4   5.0   6.0
C   7   8.0   9.0
D  10  11.0  12.0
E  13  14.0  15.0

In [ ]:
df.columns #return List of data Set Columns

Index(['X', 'Y', 'Z'], dtype='object')

In [ ]:
df.index #Return Data Set Index Value

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'], dtype='object')

In [ ]:
df.info() #Information About The Data Set

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, A to I
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       9 non-null      int64
 1   Y       8 non-null      float64
 2   Z       8 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 588.0+ bytes

In [ ]:
df.describe()

               X          Y          Z
count   9.000000   8.000000   8.000000
mean   13.000000  12.500000  13.500000
std     8.215838   7.348469   7.348469
min     1.000000   2.000000   3.000000
25%     7.000000   7.250000   8.250000
50%    13.000000  12.500000  13.500000
75%    19.000000  17.750000  18.750000
max    25.000000  23.000000  24.000000

In [ ]:
df.shape #Find The Shape Of The dataFrame

(9, 3)

In [ ]:
df['Y'] #get Values By Coloumn Name Like Filter By Colomn Name

A     2.0
B     5.0
C     8.0
D    11.0
E    14.0
F    17.0
G    20.0
H    23.0
I     NaN
Name: Y, dtype: float64

In [ ]:
#working With CSV File and Importing CSV FILE
noc_regions_data=pd.read_csv('/content/noc_regions.csv')
noc_regions_data.head()
noc_regions_data.columns
noc_regions_data.index
noc_regions_data.info()
noc_regions_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NOC     230 non-null    object
 1   region  227 non-null    object
 2   notes   21 non-null     object
dtypes: object(3)
memory usage: 5.5+ KB

        NOC   region                 notes
count   230      227                    21
unique  230      206                    21
top     AFG  Germany  Netherlands Antilles
freq      1        4                     1

In [ ]:
#working With Excel File
olympicsdf=pd.read_excel('/content/olympics-data.xlsx',sheet_name='results')
olympicsdf.head()
olympicsdf.columns
olympicsdf.index
olympicsdf.info()
olympicsdf.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  object
 2   discipline  308407 non-null  object
 3   event       308408 non-null  object
 4   as          308408 non-null  object
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  object
 7   team        121714 non-null  object
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   object
dtypes: bool(1), float64(2), int64(1), object(7)
memory usage: 23.8+ MB

                year     athlete_id          place
count  305807.000000  308408.000000  283193.000000
mean     1982.239223   72624.097125      16.102764
std        30.983982   41285.940841      19.322611
min      1896.000000       1.000000       1.000000
25%      1964.000000   34412.000000       5.000000
50%      1992.000000   73739.500000       9.000000
75%      2008.000000  107168.000000      20.000000
max      2022.000000  148986.000000     185.000000

In [ ]:
featherdf=pd.read_feather('/content/results.feather')
featherdf.head()
featherdf.columns
featherdf.index
featherdf.info()
featherdf.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  object
 2   discipline  308407 non-null  object
 3   event       308408 non-null  object
 4   as          308408 non-null  object
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  object
 7   team        121714 non-null  object
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   object
dtypes: bool(1), float64(2), int64(1), object(7)
memory usage: 23.8+ MB

                year     athlete_id          place
count  305807.000000  308408.000000  283193.000000
mean     1982.239223   72624.097125      16.102764
std        30.983982   41285.940841      19.322611
min      1896.000000       1.000000       1.000000
25%      1964.000000   34412.000000       5.000000
50%      1992.000000   73739.500000       9.000000
75%      2008.000000  107168.000000      20.000000
max      2022.000000  148986.000000     185.000000

In [ ]:
parquet=pd.read_parquet('/content/results.parquet')
parquet.head()
parquet.columns
parquet.index
parquet.info()
parquet.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  object
 2   discipline  308407 non-null  object
 3   event       308408 non-null  object
 4   as          308408 non-null  object
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  object
 7   team        121714 non-null  object
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   object
dtypes: bool(1), float64(2), int64(1), object(7)
memory usage: 23.8+ MB

                year     athlete_id          place
count  305807.000000  308408.000000  283193.000000
mean     1982.239223   72624.097125      16.102764
std        30.983982   41285.940841      19.322611
min      1896.000000       1.000000       1.000000
25%      1964.000000   34412.000000       5.000000
50%      1992.000000   73739.500000       9.000000
75%      2008.000000  107168.000000      20.000000
max      2022.000000  148986.000000     185.000000